name: Build release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Initialize MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          vsversion: '17.0'

      - name: Compile version resources
        shell: cmd
        run: |
          rc.exe /r sendto.rc

      - name: Build exe with MSVC
        shell: cmd
        run: |
          cl /O2 /MD /DUNICODE /D_UNICODE ^
            sendto.c sendto.res ^
            ole32.lib shell32.lib shlwapi.lib comctl32.lib user32.lib gdi32.lib uuid.lib ^
            /link /SUBSYSTEM:WINDOWS

      - name: Embed manifest in exe
        shell: cmd
        run: |
          mt.exe -nologo ^
            -manifest sendto.manifest ^
            -outputresource:sendto.exe;#1

      - name: Upload Setup as Artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: sendto-${{ matrix.arch }}
          path: sendto.exe

      - name: Upload Setup as Release download
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          name: sendto-${{ matrix.arch }}
          files: sendto.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
